package com.example.tictactoc.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA200BA)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6FD)
val md_theme_light_onPrimaryContainer = Color(0xFF36003E)
val md_theme_light_secondary = Color(0xFF6C586B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5DBF1)
val md_theme_light_onSecondaryContainer = Color(0xFF251626)
val md_theme_light_tertiary = Color(0xFF82524A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD4)
val md_theme_light_onTertiaryContainer = Color(0xFF33110C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEDDFE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFF7EEF2)
val md_theme_light_inverseSurface = Color(0xFF332F32)
val md_theme_light_inversePrimary = Color(0xFFFBABFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA200BA)
val md_theme_light_outlineVariant = Color(0xFFD0C3CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFBABFF)
val md_theme_dark_onPrimary = Color(0xFF580065)
val md_theme_dark_primaryContainer = Color(0xFF7C008E)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FD)
val md_theme_dark_secondary = Color(0xFFD8BFD5)
val md_theme_dark_onSecondary = Color(0xFF3B2B3B)
val md_theme_dark_secondaryContainer = Color(0xFF534152)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5DBF1)
val md_theme_dark_tertiary = Color(0xFFF6B8AD)
val md_theme_dark_onTertiary = Color(0xFF4C251F)
val md_theme_dark_tertiaryContainer = Color(0xFF673B34)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1E1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFFA200BA)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFBABFF)
val md_theme_dark_outlineVariant = Color(0xFF4D444C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFD946EF)